on:
  workflow_dispatch:
    # inputs:
    #   version:
    #     description: Version number
    #     required: true

env:
  IMAGE_NAME: ${{ github.repository }} # ghcr.io/owner/repo-name
  NODE_VERSION: 22

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest # or pin to a specific version
      - name: Install dependencies
        run: pnpm install
      - name: Bump version
        run: node .github/scripts/bumpv.js ${{ github.event.inputs.version }}
      - name: Commit and push changes
        uses: actions-js/push@master
        with:
          branch: master
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: Bump version to ${{ github.event.inputs.version }}
      - name: Build package
        run: pnpm build
      - name: Build package
        run: mkdir -p out/directus-extension-generate-types && cp -R dist out/directus-extension-generate-types/ && cp package.json out/directus-extension-generate-types/
      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: |
            out/directus-extension-generate-types
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Get version from package.json
        id: pkg
        run: echo "version=$(node -p "require('./package.json').version")" >> "$GITHUB_OUTPUT"
      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=sha,prefix={{branch}}-
            latest
            type=raw,value=${{ steps.pkg.outputs.version }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
